apiVersion: v1
kind: Template
labels:
  app: gerrit
  template: gerrit-imagestream
metadata:
  annotations:
    description: Gerrit - ImageStream
      see https://github.com/faust64/docker-gerrit
    iconClass: icon-openshift
    openshift.io/display-name: Gerrit
    tags: gerrit
  name: gerrit-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Gerrit image
    name: gerrit-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
